package com.example.pijava_fluently.entites;

public class User {

    private int    id;
    private String email;
    private String nom;
    private String prenom;
    private String statut;
    private String password;
    private String roles;
    private String faceDescriptor;
    // ── NEW ───────────────────────────────────────────────────────────────────
    private String chosenLanguage;   // e.g. "French", "Japanese" …
    private String avatarSvg;        // raw SVG string generated by Claude AI

    public User() {}

    // ── GETTERS ───────────────────────────────────────────────────────────────
    public int    getId()              { return id; }
    public String getEmail()           { return email; }
    public String getNom()             { return nom; }
    public String getPrenom()          { return prenom; }
    public String getStatut()          { return statut; }
    public String getPassword()        { return password; }
    public String getRoles()           { return roles; }
    public String getFaceDescriptor()  { return faceDescriptor; }
    public String getChosenLanguage()  { return chosenLanguage; }
    public String getAvatarSvg()       { return avatarSvg; }

    // ── SETTERS ───────────────────────────────────────────────────────────────
    public void setId(int id)                   { this.id = id; }
    public void setEmail(String email)          { this.email = email; }
    public void setNom(String nom)              { this.nom = nom; }
    public void setPrenom(String prenom)        { this.prenom = prenom; }
    public void setStatut(String statut)        { this.statut = statut; }
    public void setPassword(String password)    { this.password = password; }
    public void setRoles(String roles)          { this.roles = roles; }
    public void setFaceDescriptor(String fd)    { this.faceDescriptor = fd; }
    public void setChosenLanguage(String lang)  { this.chosenLanguage = lang; }
    public void setAvatarSvg(String svg)        { this.avatarSvg = svg; }

    // ── HELPERS ───────────────────────────────────────────────────────────────
    public boolean isAdmin() {
        return roles != null && roles.contains("ROLE_ADMIN");
    }

    /** True when the user has already gone through the language-picker screen. */
    public boolean hasAvatar() {
        return avatarSvg != null && !avatarSvg.isBlank();
    }

    @Override
    public String toString() {
        return prenom + " " + nom + " <" + email + ">";
    }
}